version: "3.3"
services:
    gazpar:
        container_name: gazpar
        image: gazpar:latest
        build: .
        restart: unless-stopped
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
        command: ["gazinflux.py", "--days", "10", "--schedule", "12:00"]
        restart: unless-stopped
        # environment:
        #     - GRDF_USERNAME=username
        #     - GRDF_PASSWORD=password
        #     - GRDF_PCE=123456789ABCDE
        #     - INFLUXDB_HOST=192.168.0.2
        #     - INFLUXDB_DATABASE=db_name
        #     - INFLUXDB_USERNAME=db_username
        #     - INFLUXDB_PORT=8086
        #     - INFLUXDB_SSL=false
        #     - INFLUXDB_VERIFY_SSL=false
        #     - INFLUXDB_PASSWORD=db_password
        #     - MQTT_HOST=192.168.0.22
        #     - MQTT_PORT=1883
        #     - MQTT_KEEPALIVE=60
        #     - MQTT_TOPIC=topic/gazpar
